Create model currence and pydantic schemas
currency-exchange-rates/exchange_rate pull request #16
Opened 2024-12-16 15:28 UTC by BlopFlop

2024-12-16 15:36 UTC, hixwizard approved these changes

2024-12-17 04:06 UTC, margoloko commented
> _ No description provided. _

по поводу наименований веток и ПР- посмотри в чате https://t.me/c/2321433355/99/381 . требования от ревьюера

2024-12-17 10:17 UTC, margoloko requested changes

2024-12-17 10:17 UTC, margoloko commented on src/utils.py
удали пустые файлы

2024-12-17 10:17 UTC, margoloko commented on src/views.py
тоже

2024-12-17 10:17 UTC, margoloko commented on migrations/README
> +Single-database configuration for Flask.
а файлы с миграциями обязательно нужны в репе?

2024-12-17 10:17 UTC, margoloko commented on src/repository.py
> +    """Base CRUD operations in current application."""
давайте определимся с докстрингом- на каком языке всё будем описывать

2024-12-17 10:17 UTC, margoloko commented on src/schemas.py
> +            )
raise ValueError(except_message)

2024-12-17 10:17 UTC, margoloko commented on src/models.py
> +        CheckConstraint("LENGTH(name) <= 100", name="check_len_name"),
name="check_len_name" предлагаю поправить на name="check_len_country", чтоб не дублировалось, как выше

2024-12-17 11:32 UTC, margoloko approved these changes

2024-12-17 11:33 UTC, merged